### ISSUE TITLE
[Bug] crash upon launch.

### ISSUE THREAD

**Issue by Kingdomall** [LeeTheSoloGamer/LeesCreatures#6]
The log explains it all.
The game launches just fine, When I try to load into a world, it crashes and gives me this error:
I'm using your latest version 1.0.9 with 1.16.5 - 36.1.18 Forge and I have all the proper dependencies and such.

---- Minecraft Crash Report ----
// There are four lights!

Time: 5/15/21 1:54 PM
Description: Registering texture

java.lang.NullPointerException: Registering texture
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:59) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureData.func_217799_a(SourceFile:81) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.texture.SimpleTexture.func_215246_b(SourceFile:57) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.renderer.texture.SimpleTexture.func_195413_a(SourceFile:28) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.renderer.texture.TextureManager.func_230183_b_(TextureManager.java:94) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.texture.TextureManager.func_229263_a_(TextureManager.java:65) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.texture.TextureManager.func_229269_d_(TextureManager.java:58) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:140) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.func_225623_a_(GeoEntityRenderer.java:41) ~[?:3.0.35] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.EntityRendererManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.18.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$489/1602288195.call(Unknown Source) [forge-1.16.5-36.1.18.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

**Comment by LeeTheSoloGamer** [comment]
use geckolib v3.0.6

**Comment by Kingdomall** [comment]
> use geckolib v3.0.6

I do not see a v3.0.6 for 1.16.5... and if it exists, don't you think that's REALLY far back?

**Comment by LeeTheSoloGamer** [comment]
there are some issues with the newer version of geckolib with the mod. we will try to fix this issue but for now thats the version recommend
