### ISSUE TITLE
CrystalWyvern crashes 

### ISSUE THREAD

**Issue by BlackAures1** [LeeTheSoloGamer/LeesCreatures#9]
Stably crashes when trying to naturally spawn a crystal wyvern on a large modpack. 

```
java.lang.ClassCastException: net.minecraft.block.Block cannot be cast to net.minecraft.tags.ITag
	at com.leethesologamer.leescreatures.entities.CrystalWyvernEntity.canCrystalWyvernSpawn(CrystalWyvernEntity.java:164) ~[?:1.0] {re:classloading}
	at com.leethesologamer.leescreatures.world.ModEntitySpawing$$Lambda$15664/731662979.test(Unknown Source) ~[?:?] {}
	at net.minecraft.entity.EntitySpawnPlacementRegistry.func_223515_a(EntitySpawnPlacementRegistry.java:60) ~[?:?] {re:classloading,pl:accesstransformer:B}
```
	
[crash-2021-08-31_13.46.14-client.txt](https://github.com/LeeTheSoloGamer/LeesCreatures/files/7110078/crash-2021-08-31_13.46.14-client.txt)
[crash-2021-08-31_14.06.34-server.txt](https://github.com/LeeTheSoloGamer/LeesCreatures/files/7110079/crash-2021-08-31_14.06.34-server.txt)

**Comment by Niconoko** [comment]
Me got the same crash as well.

**Comment by LeeTheSoloGamer** [comment]
try removing mods

**Comment by BlackAures1** [comment]
I only need this mod inside the modpack, so I do not see the point of removing it just to check. I'm sure it works on the clean version, but let the developer handle it.   I just warned about it and removed the mod.

**Comment by LeeTheSoloGamer** [comment]
after looking at the code i found the issue

**Comment by Reshirou** [comment]
Got the same crash from Crystal Wyvern spawning.

**Comment by BlackAures1** [comment]
Crashes are still there. Even with the gamerule, which disables spawn creatures.

[crash-2021-10-29_03.48.27-server.txt](https://github.com/LeeTheSoloGamer/LeesCreatures/files/7438260/crash-2021-10-29_03.48.27-server.txt)
[crash-2021-10-29_03.55.50-server.txt](https://github.com/LeeTheSoloGamer/LeesCreatures/files/7438261/crash-2021-10-29_03.55.50-server.txt)
[crash-2021-10-29_04.23.12-server.txt](https://github.com/LeeTheSoloGamer/LeesCreatures/files/7438262/crash-2021-10-29_04.23.12-server.txt)
[crash-2021-10-29_03.39.58-server.txt](https://github.com/LeeTheSoloGamer/LeesCreatures/files/7438263/crash-2021-10-29_03.39.58-server.txt)

**Comment by inkdear** [comment]
Got the same crash with only a few mods in.
[crash-2021-12-14_13.47.14-server.txt](https://github.com/LeeTheSoloGamer/LeesCreatures/files/7707808/crash-2021-12-14_13.47.14-server.txt)

**Comment by RoRo-Fdez** [comment]
In the same way, I play in version 1.16.5 and when trying to use the Crystal Wyvern the game crashes with the version of mod 1.0.9, I hope you can fix this problem soon because I really like this trend and I would like to use it without problems , I thank you in advance for reading me.

**Comment by RoRo-Fdez** [comment]
In the same way, I play in version 1.16.5 and when trying to use the Crystal Wyvern the game crashes with the version of mod 1.0.9, I hope you can fix this problem soon because I really like this trend and I would like to use it without problems , I thank you in advance for reading me.

**Comment by RoRo-Fdez** [comment]
In the same way, I play in version 1.16.5 and when trying to use the Crystal Wyvern the game crashes with the version of mod 1.0.9, also the Crystal Wyvern still cannot be controlled when mounted, I hope you can fix this problem soon. I really like this mod and I would like to use it without problems, I thank you in advance for reading me.

**Comment by Kori321** [comment]
[1.16.5] Same problem.
[crash CrystalWyvernEntity.txt](https://github.com/LeeTheSoloGamer/LeesCreatures/files/11225302/crash.CrystalWyvernEntity.txt)
